brefphp/aws-lambda-layers

- php-80/cpu-arm.Dockerfile
- php-80/cpu-x86.Dockerfile
- php-81/cpu-x86.Dockerfile
That way we *know* which version is actually installed, instead of the versions depending on _when_ the layers were built.
That will also help with the general flow: contributors can send PRs to increase PHP versions when they come out. Instead of randomly having to rebuild layers in the hopes that it will bundle a new PHP version.
> Specify PHP versions explicitly

- utils/lambda-publish/Makefile
Closes #28 
Recently a new AWS region was launched in Europe/Spain
This PR adds support for "eu-south-2" and pushes layers to that region also
> Support Europe/Spain region

- php-80/cpu-arm.Dockerfile
- tests/test_3_manual_enabling_extensions.php
https://github.com/brefphp/bref/issues/1043
APCu was the last extension missing from ARM runtimes.
It is not provided by Amazon Linux 2. The only option left is to compile it (`pecl install apcu`).
That means installing all the "devel" tools, which adds some extra time to the build (maybe 30s, so it's tolerable). I think anyway we will have to add these extra dev tools anyway to support bref-extra extensions, which almost always compile from scratch.
So this move is not just for ARM and APCu. After merging I plan on adding the same thing (install dev tools) to x86 images.
> Install APCu in ARM layers

- README.md
- cpu-arm.Makefile
- cpu-x86.Makefile
- docker-compose.yml
- php-80/cpu-arm.Dockerfile
- php-80/cpu-x86.Dockerfile
- php-81/cpu-x86.Dockerfile
- php-82/cpu-x86.Dockerfile
This provides the `bref/build-php-80` images used to compile extra extensions.
Check out #31 for a bit more context.
> Provide `build-` images like Bref 1 to allow building extra extensions

- .github/workflows/release-base-devel-image.yml
- base-devel/Makefile
- base-devel/README.md
- base-devel/cpu-arm.Dockerfile
- base-devel/cpu-x86.Dockerfile
- base-devel/docker-compose.yml
- php-80/cpu-arm.Dockerfile
- php-80/cpu-x86.Dockerfile
- php-81/cpu-x86.Dockerfile
- php-82/cpu-x86.Dockerfile
This introduces new `bref/base-devel-x86` and `bref/base-devel-arm` images that are built asynchronously (every week).
These images pre-install Amazon Linux dev tools, so that this expensive operation isn't performed when we actually build the layers. Since these operations are not related to the PHP version, or every the current day (i.e. those are basic system installs), we can run these asynchronously and hopefully accelerate the builds.
> Optimize the build by publishing a "base-devel" image ahead of time

- .github/workflows/tests.yml
That will avoid the need for a Depot token, and will solve the problem of that token not being available in pull request builds.
> Use the official Depot action to auth via OICD

- .github/workflows/tests.yml
This should fix the failure seen in #47. 
This is an annoying GitHub limitation - GitHub blocks access to all repository secrets and the OIDC token endpoint for PRs that originate from fork repos. This is a security feature, to prevent PRs from exfiltrating secrets, but also means there's no way at the moment to authenticate with your Depot builder. Workflows for `push` work, and workflows for `pull_request`s work if they originate from within this repo, just not from forks.
We have a few ideas we've been exploring for how to work around this limitation, and we're trying to get in touch with GitHub as well to see if there's a better long-term solution, but in the meantime, our recommended workaround is to fall back to local `buildx bake` for fork PRs.
This PR modifies the tests workflow …
> Use local buildx for third-party PR builds

- README.md
- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- tests/test_2_extensions.php
- tests/utils.php
- utils/lib-copy/copy-dependencies.php
I noticed some differences in libs packaged inside layers for Bref v2.
Here's a comparison with v1: https://gist.github.com/mnapoli/99a46134a7d93e440480888ae29e94ff
I noticed that some libs we compile are not shipped in the layers, and I think I tracked that bug to the utility that copies system libraries. I am adding some tests and will fix that in that PR.
> Fix missing libraries bundled in layers

- utils/lib-copy/copy-dependencies.php
- auto-create the target directory
- do not silence "dependency not found" anymore
> Improve the script that copies system dependencies

- Makefile
- docker-bake.hcl
- layers/console/Dockerfile
- layers/fpm-dev/Dockerfile
- tests/Makefile
- utils/docker-zip-dir.sh
> Merge Docker images by making them multi-platform

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- tests/test_2_extensions.php
This file can be referenced directly by users, e.g. to use PlanetScale. Let's ensure it doesn't move accidentally.
> Move the certs file to the same location as Bref v1

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- tests/test_2_extensions.php
Closes https://github.com/brefphp/aws-lambda-layers/issues/73. Note that we are using 3.0.x LTS, not 3.x (3.1.x is not LTS, and it's not clear if PHP actually supports it).
> Use OpenSSL 3.0 LTS on PHP 8.1 and 8.2

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
1. This upgrade applies only to PHP 8.1 and 8.2.
2. I've also fixed Fix NGHTTP2 warnings due to no libxml2 - I can move this to another PR if needed.
> Enable TLS 1.3 and upgrade to cURL 8.1.0

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
The segfaults I was seeing previously were ultimately caused by the nghttp2 library not being linked correctly in Laravel Vapor, and so the cURL upgrade in bref is fine to do, even on OpenSSL 1.1.x for PHP 8.0. It's nice that we can finally get all the security and bug fixes to cURL into all bref runtimes.
> Upgrade to cURL 8.1.1 and backport changes to PHP 8.0 too

- layers/console/bootstrap.sh
- layers/fpm/bootstrap.sh
- layers/function/bootstrap.sh
The `bootstrap.sh` is always exporting the `RUNTIME_CLASS` variable, this PR will only set the variable if it is not already defined in the environment.
This also updates the `while` style code... Happy to undo that if needed.
> Check if the RUNTIME_CLASS is already set

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
Just like in bref 1.x, because Amazon have not updated their version in a long time, and it has security issues.
> Use newer zlib than shipped in AL2

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
> Document zlib install

- .github/workflows/release.yml
- .github/workflows/tests.yml
Fixes a deprecation warnings, and makes sure things don't break on us next year when github start to change the ubuntu latest alias - we wanna explicitly control when to move, just like the other action major versions.
> GitHub Actions version upgrades and pins

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
Fixes [CVE-2023-44487](https://github.com/nghttp2/nghttp2/security/advisories/GHSA-vx74-f528-fxqg).
> Bump nghttp2 to 1.57.0

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
Fixes [CVE-2023-38545](https://curl.se/docs/CVE-2023-38545.html) and [CVE-2023-38546](https://curl.se/docs/CVE-2023-38546.html).
> Bump to cURL 8.4.0

- .github/workflows/release.yml
- .github/workflows/tests.yml
Moves off of EOL node (16 -> 20) with known security vulnerabilities (already!).
> Bumped actions versions

- layers/bootstrap.php
This PR is in relation to https://github.com/brefphp/constructs/issues/12
By checking for the file to exist before `require`ing it we allow the later thrown exception to flow out as intended.
> Add file_exists check to prevent early require fatal

- .github/workflows/release.yml
- Makefile
So in Docker Hub we have tags:
- `latest`
- `2`
- `2.1.8`
Allowing users to pinpoint a specific version and control upgrades.
> Tag Docker images for patch versions too

- layers/fpm-dev/Dockerfile
When support for PHP 8.3.0beta1 was added in #91, PHP 8.3 was excluded from the xdebug installation.
So we have made sure to install xdebug with PHP 8.3.0.
> Installed xdebug with PHP 8.3.0

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
Prior to cURL 8.6.0, configure would silently skip when libpsl was missing, compiling without support for public suffix lists. For Bref v2 at least, I think it's probably a good idea to compile cURL with support for this, so I've added in a build step to compile libpsl.
For Bref v1 (https://github.com/brefphp/bref/pull/1729), I'm not sure it's such a good idea to start making what is arguably a breaking change, so I've added in the configure flag to continue to ignore the fact that libpsl is missing.
> curl 8.6.0

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
Note that the addition of `--without-icu` is not a change. The difference is just that `--with-icu` in postgres 15 was swapped out for `--without-icu` in postgres 16. Newer postgres clients are backwards compatible with older versions, so this change should be pretty safe. Notably, this new version (and also the corresponding 15.6 release) support OpenSSL 3.2, which has been bumped in a follow-up (#162).
---
Closes #144.
> postgres 16.2

- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- tests/test_2_extensions.php
Blocked by #161 which upgrades us to Postgres 16.2. Postgres 15.5 does not support OpenSSL 15.5 (#144), but Postgres 16.2 does (and so does the corresponding 15.6 Postgres release, actually). OpenSSL 3.2 should remediate some of the performance problems reported in https://github.com/brefphp/bref/issues/1528.
> OpenSSL 3.2.1

- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
FYI, there will be no corresponding PR for PHP 8.0 nor Bref v1 as they are using 2.11.7 and should not be switched to the 2.12.x series.
> Bump libxml2 to 2.12.6

- layers/fpm-dev/Dockerfile
Helpful to install prod dependencies before deploying (and run in the same env as prod).
> Add composer to the dev images

- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
* Support updated to oqs-provider 0.6.0
* Add demo for ECDH key exchange
* Fixes for various memory leaks
* Various build and behavioral fixes on VMS
* Various fixes in response to CVE-2024-4741
* Fix race for X509 store found by thread sanitizer
* Various bug fixes to the QUIC client
* Explicit setup of cpuid flags in the fips provider
* DSA size checking (CVE-2024-4603)
* Fix for an sm2 encryption implementation bug
* Addition of a linux-arm64ilp32-clang build target
* Various fixes for CVE-2024-2511
* Fix unconstrained session cache growth in TLSv1.3 (CVE-2024-2511)
* Fix unbounded memory growth when using no-cached-fetch
* Add atexit configuration option to using atexit() in libcrypto at build-time
* Fix sm4-xts aarch64 assembly implementation bug
* Fix compilation on Windows using …
> Upgrade OpenSSL to 3.3.1

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
* Building with `zig build` now requires Zig 0.12.
* When using the traditional build system, -O3 is used instead of -Ofast.
* Improved detection of the compiler flags required on aarch64.
* mproved compatibility with custom build systems on aarch64.
* apple-xcframework: VisionOS packages are not built if Xcode doesn't include that SDK.
* `crypto_kdf_hkdf_sha512_statebytes()` was added.
* When using Visual Studio, runtime CPU feature detection is now enabled on Windows/aarch64.
* There were issues with C++ guards affecting usage of libsodium using Swift on Windows. This has been fixed.
* Emscripten: `crypto_aead_aegis*()` functions are now exported in JavaScript builds
* Emscripten: unsupported `--memory-init-file` option has been removed.
* apple-xcframework: the minimal deployment …
> Upgrade libsodium to 1.0.20

- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- CGI:
. Fixed bug GHSA-3qgc-jrrr-25jv (Bypass of CVE-2012-1823, Argument Injection
in PHP-CGI). (CVE-2024-4577) (nielsdos)
- Filter:
. Fixed bug GHSA-w8qr-v226-r27w (Filter bypass in filter_var FILTER_VALIDATE_URL).
(CVE-2024-5458) (nielsdos)
- OpenSSL:
. The openssl_private_decrypt function in PHP, when using PKCS1 padding
(OPENSSL_PKCS1_PADDING, which is the default), is vulnerable to the Marvin Attack
unless it is used with an OpenSSL version that includes the changes from this pull
request: https://github.com/openssl/openssl/pull/13817 (rsa_pkcs1_implicit_rejection).
These changes are part of OpenSSL 3.2 and have also been backported to stable
versions of various Linux distributions, as well as to the PHP builds provided for
Windows since the previous release. All distributors and …
> Upgrade PHP to 8.1.29, 8.2.20, 8.3.8

- php-84/Dockerfile
> Upgrade to PHP 8.4.0 alpha2

- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
> Upgrade SQLite on both PHP 8.2 and 8.3

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
cURL 8.9.1 was released today with some important bug fixes and security fix. It is compatible with all PHP versions Bref supports.
> Upgrade to cURL 8.9.1

- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
PHP 8.2.22, 8.3.10, 8.4.0alpha4 were released today, and libxml2 2.13.3 is the latest version. The 2.13.x series of libxml2 is not compatible with PHP older than 8.2.22 (including 8.0.x, 8.1.x), 8.3.x older than 8.3.10, and 8.4.x older than alpha2.
> PHP 8.2.22, 8.3.10, 8.4.0alpha4 and libxml2 2.13.3

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
> PHP 8.4.0beta5

- layers/bootstrap.php
Fix https://github.com/brefphp/bref/issues/1867
> Improve error handling when Composer dependencies are missing

- layers/fpm-dev/Dockerfile
- php-84/Dockerfile
> Upgrade to PHP 8.4.0RC2 and install Xdebug

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
- tests/test_2_extensions.php
After chatting about this [here](https://github.com/brefphp/bref/issues/1888#issuecomment-2812097709), I've tried enabling the FFI extension to allow the use of the [libsql-php](https://github.com/tursodatabase/libsql-php) library.
> Enable FFI extension

- layers/bootstrap.php
In the `fpm` runtime, fatal errors in the bootstrap process don't have their details logged.
Reported in Slack: https://brefworkspace.slack.com/archives/C057S6G4Z9N/p1750813674579189?thread_ts=1750740077.495139&cid=C057S6G4Z9N
Here is to illustrate:
- FPM runtime (no error details)
- Function runtime
The reason is that `display_errors=0` in the FPM runtime because we don't want errors in the application to be logged to `stdout` (because `stdout` is the HTTP response). However this is an issue in the bootstrap process: errors are then not logged (some errors, not all of them).
This PR forces `display_errors=1` in the bootstrap process regardless of the runtime.
> Fix some internal fatal errors not logged by forcing `display_errors=1` in the bootstrap process

- .github/workflows/tests.yml
- Makefile
- layers/fpm-dev/Dockerfile
- layers/fpm/bref.ini
- layers/function/bref.ini
- layers/opcache.ini
- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
- php-85/Dockerfile
- tests/Makefile
Notable changes since PHP 8.4 impacting us:
* The opcache extension is no longer an extension as such and is part of core.
* A newer version of ICU is required, so we're building the latest from source.
* Xdebug doesn't support PHP 8.5 yet, so we're skipping installing it for now.
> Add PHP 8.5 support

- php-83/Dockerfile
- php-84/Dockerfile
- php-85/Dockerfile
> Upgrade PHP AL2023

- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
> Upgrade to openssl 3.5.4 LTS
