- .github/workflows/tests.yml
> Fix building ARM images on GitHub Actions

- cpu-x86.Makefile
- layers/docker-compose.yml
> Build the bref/fpm-dev-gateway image

- .github/workflows/release.yml
When new layers are released, bref/bref layers.json will be updated automatically.
> Trigger layer versions update after release

- utils/lambda-publish/Makefile
> Fix #7 Add extra regions already supported by Bref 1

- layers/fpm/bref-extensions.ini
- layers/function/bref-extensions.ini
- php-80/cpu-arm.Dockerfile
- php-80/cpu-x86.Dockerfile
- php-81/cpu-x86.Dockerfile
- tests/test_2_extensions.php
To be backwards compatible with Bref 1
Fix #23
> Fix #23 Add the zip core extension

- php-80/cpu-arm.Dockerfile
> Upgrade PHP 8.0 ARM

- cpu-x86.Makefile
- docker-compose.yml
- php-82/cpu-x86.Dockerfile
- tests/Makefile
- tests/docker-compose.yml
Fixes #16
TODO:
See https://github.com/remicollet/remirepo/issues/206
> #16 Add PHP 8.2 x86 layers

- php-80/cpu-x86.Dockerfile
- php-81/cpu-x86.Dockerfile
See https://github.com/remicollet/remirepo/issues/206#issuecomment-1304427586
> Switch to the module distribution of remi-repo

- php-82/cpu-x86.Dockerfile
> Upgrade to PHP 8.2.0 stable

- .github/workflows/release.yml
- cpu-arm.Makefile
- cpu-x86.Makefile
> Fix #9 Publish v2 Docker images

- layers/fpm/composer.json
> Upgrade to the stable version of the FPM runtime

- cpu-arm.Makefile
- php-81/cpu-arm.Dockerfile
PHP 8.1 is now available in Amazon Linux Extras : https://github.com/brefphp/bref/discussions/1357#discussioncomment-4410432
> Add PHP 8.1 for ARM runtimes

- layers/fpm/bootstrap.sh
- layers/function/bootstrap.sh
- tests/Makefile
- tests/docker-compose.yml
- tests/test_4_function_handler.php
- tests/test_7_custom_ini_scan_dir.php
Fix https://github.com/brefphp/bref/issues/1362
> Allow overriding INI path

- layers/console/composer.json
- layers/fpm/composer.json
> Upgrade dependencies

- php-81/Dockerfile
- php-82/Dockerfile
> Upgrade to PHP 8.1.15 and 8.2.2

- layers/console/composer.json
- layers/fpm/composer.json
> Update dependencies to support Bref hooks

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- tests/test_2_extensions.php
> Fix #53: embed the OpenSSL certificates file in the layers

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
> Upgrade to postgres 15.2

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
Noticed in https://github.com/brefphp/extra-php-extensions/pull/406 this variable is useful to build some extensions in https://github.com/brefphp/extra-php-extensions
> Export the `PHP_BUILD_DIR` variable to build extra extensions

- Makefile
- docker-bake.hcl
- layers/console/Dockerfile
- layers/fpm-dev/Dockerfile
- tests/Makefile
- utils/docker-zip-dir.sh
See https://github.com/brefphp/aws-lambda-layers/issues/62#issuecomment-1467790855
> Revert #65

- layers/fpm-dev/Dockerfile
- tests/Makefile
- tests/test_2_extensions.php
Fix https://github.com/brefphp/bref/issues/1455
> Fix fpm-dev extensions not loaded

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
> Update to PHP 8.0.28, 8.1.17, 8.2.4

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
Fixes CVE-2023-29469 and CVE-2023-28484.
> Upgrade libxml2 to 2.10.4

- php-81/Dockerfile
- php-82/Dockerfile
> Upgrade to PHP 8.1.18 and 8.2.5

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
> Upgrade to OpenSSL 1.1.1u and 3.0.9

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
~Draft until tomorrow, since sometimes re-tagging happens.~ :shipit:
> Upgrade to PHP 8.0.29, 8.1.20 and 8.2.7

- layers/fpm-dev/Dockerfile
> Bumped blackfire version to 1.87.2

- layers/console/bootstrap.sh
- layers/fpm/bootstrap.sh
- layers/function/bootstrap.sh
> Avoid hardcoding the PHP binary location

- .github/aws/github-role.yml
https://github.blog/changelog/2023-06-27-github-actions-update-on-oidc-integration-with-aws/
> Fix deployment following OIDC GitHub changes

- .github/workflows/tests.yml
- Makefile
- layers/fpm-dev/Dockerfile
- php-83/Dockerfile
- tests/Makefile
~WIP: waiting on the download URL, as it will be namespaced to one of the release managers.~
~UPDATE: When ~alpha3~beta1 is released, this PR should be ready.~ 🚢
> Provide PHP 8.3.0beta1 support

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
Will be ready to merge on Wednesday.
> Upgrade curl to 8.2.1 and nghttp2 to 1.55.1

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
PR draft until the tarballs are final - there has already been one re-tag so far.
> PHP 8.0.30, 8.1.22, 8.2.9, 8.3.0beta2

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
> Upgrade to libzip 1.10.1

- php-83/Dockerfile
> PHP 8.3.0beta3

- php-80/Dockerfile
I am expecting a 3.0.x release later in the week, and will follow-up with a 2nd PR.
> Bumped openssl to 1.1.1w

- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
> Upgrade to openssl 3.0.11

- layers/fpm-dev/Dockerfile
https://github.com/nodesource/distributions/issues/1664#issuecomment-1731412774
> Fix installation of node for container image

- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
> PHP 8.1.4, 8.2.11, 8.3.0RC3

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
> Upgrade to oniguruma 6.9.9

- php-83/Dockerfile
> Upgrade to PHP 8.3.0RC6

- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- tests/test_2_extensions.php
> Use OpenSSL 3.2.0 on PHP 8.1+

- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- tests/test_2_extensions.php
Reverts brefphp/aws-lambda-layers#143
See #144
> Revert "Use OpenSSL 3.2.0 on PHP 8.1+"

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
> curl 8.5.0

- php-82/Dockerfile
- php-83/Dockerfile
> PHP 8.2.15 and 8.3.2

- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
> Bump libxml2 to 2.12.4 on PHP 8.1+

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
> Upgrade nghttp2 to 1.59.0

- php-82/Dockerfile
- php-83/Dockerfile
> OpenSSL 3.0.13

- php-82/Dockerfile
- php-83/Dockerfile
Latest PHP 8.2 and 8.3 versions (no 8.1.x release this time month).
> Upgrade to PHP 8.2.16 and 8.3.3

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
> Bump nghttp2 to 1.60.0

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
> Bumped cURL to 8.7.1

- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
> Upgrade to OpenSSL 3.3.0

- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
> Upgrade PHP versions

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- tests/test_2_extensions.php
> Added openssl.cnf to bref layer

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
> Upgrade nghttp2 to 1.62.1 and curl to 8.8.0

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
> Upgrade to postgres 16.3

- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
> Upgrade libxml2 to 2.12.8

- .github/workflows/tests.yml
- php-84/Dockerfile
cf [PHP 8.4.0 Alpha 1 available for testing](https://www.php.net/archive/2024.php#2024-07-05-1)
> add PHP 8.4.0 (alpha1)

- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
> Upgrade SQLite on both PHP 8.2 and 8.3

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
> Upgrade to cURL 8.9.0

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
> libxml2 security patches

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
> Upgrade PostgreSQL from 16.3 to 16.4

- utils/lib-copy/copy-dependencies.php
- utils/lib-copy/libs-arm.txt
- utils/lib-copy/libs-x86.txt
Related to https://github.com/brefphp/extra-php-extensions/issues/443
> Fix support for `libgpgme`

- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
> Upgrade sqlite to 3.46.1

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
> Bump nghttp2 to 1.63.0

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
> cURL 8.10.0

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
> Upgrade to cURL 8.10.1

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
> Upgrade libzip to 1.11.1

- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
> Upgrade to PHP 8.2.24, 8.3.12, 8.4.0RC1

- php-81/Dockerfile
Looks like this also got released today.
> PHP 8.1.30

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
> Upgrade nghttp2 to 1.64.0

- php-82/Dockerfile
- php-83/Dockerfile
- https://www.php.net/archive/2024.php#2024-10-24-1
- https://www.php.net/archive/2024.php#2024-10-24-2
> Upgrade to PHP 8.3.13, 8.2.25

- php-84/Dockerfile
cf https://www.php.net/archive/2024.php#2024-11-07-1
> Update to PHP 8.4.0RC4

- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
> Upgrade libxml2 to 2.13.5

- php-84/Dockerfile
*not yet, but this should works
> PHP 8.4 released 🥳

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
> Upgrade to postgres 17.2

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
Released today with many bug fixes and one low-sev CVE.
> Upgrade to cURL 8.11.1

- layers/fpm-dev/Dockerfile
> Use xdebug 3.4.0

- php-83/Dockerfile
- php-84/Dockerfile
> PHP 8.3.16 and 8.4.3

- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
> Upgrade to sqlite to 3.48.0

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
> Upgrade oniguruma to 6.9.10

- layers/fpm-dev/Dockerfile
> Upgrade xdebug to 3.4.1

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
> Upgrade to libzip 1.11.3

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
> Upgrade to cURL 8.12.0

- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
Fixes CVE-2025-24928 and CVE-2024-56171.
> Upgrade to libxml2 2.12.10 and 2.13.6

- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
Reverts brefphp/aws-lambda-layers#234
> Revert "Upgrade to OpenSSL 3.4.1"

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
This is an out of cycle release that fixes CVE-2025-1094.
> Upgrade to  PostgreSQL 17.4

- layers/fpm-dev/Dockerfile
> xdebug 3.4.2

- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
> Upgrade libxml2 to 2.13.7

- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
Upgrade to libxml2 2.13.8 on supported PHP versions.
> Upgrade to libxml2 2.13.8

- Makefile
> Fail the job on Docker push error

- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
> Upgrade to sqlite 3.49.2

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
> Upgrade to postgres 17.5

- php-83/Dockerfile
- php-84/Dockerfile
> Upgrade PHP to 8.3.21 and 8.4.7

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
> Upgrade to curl 8.14.0

- php-83/Dockerfile
- php-84/Dockerfile
> Upgrade to PHP 8.3.22 and 8.4.8

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
> Upgrade to nghttp2 1.66.0

- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
We should release this as a minor version bump, and re-build extensions on the new layers.
> Upgrade to OpenSSL 3.5.1

- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
> Upgrade sqlite to 3.50.3

- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
> SQLite 3.50.4

- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
> Upgrade to openssl 3.5.2

- php-80/Dockerfile
- php-81/Dockerfile
- php-82/Dockerfile
- php-83/Dockerfile
- php-84/Dockerfile
Fixes CVE-2025-10148 and CVE-2025-9086.
> Upgrade curl and nghttp2
